### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by RyanLangston** [Adorable-Catgirl/Zorya-NEO#5]
I'm a bit confused, how exactly are we supposed to install this into minecraft, wget or something?

**Comment by lunaboards-dev** [comment]
so, there's two options

first option, releases:
1. go to github releases
2. right click on latest `zorya-neo-installer.lua`
3. click "copy link location"
4. wget this url!
5. run installer
6. ???
7. profit

alternatively, you can build it yourself:
1. install luacomp, luamin, and lua lanes
2. clone the repo's master branch
3. `lua luabuild.lua all`
4. grab releases from the releases directory
5. i usually just upload them to 0x0.st
6. wget into game
7. install
8. profit
