### ISSUE TITLE
Issue installing the files

### ISSUE THREAD

**Issue by PublicVoidUpdate** [Adorable-Catgirl/Zorya-NEO#6]
I am using Opendisks to create a floppy I was trying to install the files from, I also renamed the first installer so I wouldn't have to remember to install it first. The specific error is in the attached picture. I am using 1.12.2 minecraft with the latest installer of Zorya Neo. 

Error:
"Unexpected symbol near '<':![20210407_210203.jpg](https://user-images.githubusercontent.com/81382069/113962437-eb3e5300-97e4-11eb-8e1d-4c0cc9753aae.jpg)

**Comment by bornikfik** [comment]
same problem :/

**Comment by lunaboards-dev** [comment]
Switch the CPU arch to Lua 5.3. It has to do with either the archive util and the LZSS decompressor.

**Comment by PublicVoidUpdate** [comment]
I also get a "Unrecoverable  Error bios.lua:75: No boot image!"
this is after i fixed the issue with lua 5.3 btw

**Comment by lunaboards-dev** [comment]
So, now that I look at my own code, you'll need to specify the drive to install Zorya's modules to as an argument to the installer. It normally uses the drive the computer booted from, but, in this case, the drive wasn't the one you intend to load Zorya off of. Remember to write the _entire_ address.
